version: '3.8'
networks:
  brikl_task_dev_net:
    driver: bridge

volumes:
  brikl_task_dev_persitance_postgresql:

services:
  database:
    image: postgres:14
    container_name: database.$DOMAIN
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - brikl_task_dev_net
    volumes:
      - brikl_task_dev_persitance_postgresql:/var/lib/postgresql/data:rw

  task_service:
    image: $IMAGE_NAME/task_service:$VERSION
    container_name: task_service.$DOMAIN
    ports:
      - 3000:3000
    environment:
      TZ: Asia/Bangkok
      DB_URL: $DB_URL
    networks:
      - brikl_task_dev_net
